name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    #services:
      #hub:
        #image: selenoid/chrome:89.0
      #chrome:
        #image: selenium/node-chrome
        #env:
          #HUB_HOST: hub
          #HUB_PORT: 4444  
    steps:
    - uses: actions/checkout@v2
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: selenoid status
      run: docker ps -a
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        SELENIUM_HUB_HOST: 'localhost'
      run: dotnet test --no-build --verbosity normal
      
