name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      hub:
        image: selenoid/chrome:89.0
      #chrome:
        #image: selenium/node-chrome
        #env:
          #HUB_HOST: hub
          #HUB_PORT: 4444  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: selenoid status
      run: docker selenoid/chrome:89.0 status
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
